### ISSUE TITLE
Failed to spawn command proselint. Make sure proselint is installed and on your PATH

### ISSUE THREAD

**Issue by bonfield** [AtomLinter/linter-proselint#11]
I'm running Atom 1.6.0 and linter 1.11.4 -- the latest versions -- on the latest version of OS X. I've installed linter-alex, linter-write-good, and wordcount through the Atom package manager and all three are working fine. Unfortunately, I get the error in the subject line when I save documents if linter-proselint is enabled. Also, it doesn't seem to be working at all, in terms of making suggestions. I've tried starting Atom from the command line and I still get the same errors.

**Comment by Arcanemagus** [comment]
Do you have `proselint` installed?

**Comment by bonfield** [comment]
Ah, got it. Sorry. I got used to packages installing all of their own dependencies. Now I get what "Dependencies" means. For others who may be similarly confused, I had to run

```
sudo easy_install pip
sudo pip install proselint
```

And you can check that proselint is installed by running

`proselint -v`

which displays the proselint version number. 

Also, as a reminder to others who find this thread, you have to save the document with an extension that triggers linter, such as .txt or .md, and, upon saving, linter-proselint will make recommendations.

Thanks for working on this package! I enjoy using it and it's improving my writing.

**Comment by Arcanemagus** [comment]
Although it's possible to bundle the dependencies for Node modules, for external programs like `proselint` it isn't possible to do that from within Atom.

Glad you got it figured out and if you want to submit a PR updating the readme with the information from your post there I'm sure that @smockle would appreciate it :wink:.
