### ISSUE TITLE
Line and column number reported by ProseLint is always off by one

### ISSUE THREAD

**Issue by rsmeral** [AtomLinter/linter-proselint#19]
For example, when an issue is actually at 6:6, the report says it's at 7:7. This happens for all issues.

Happens for me on Markdown-formatted documents with linter-proselint 3.0.0 and Atom 1.6.2.

**Comment by Arcanemagus** [comment]
@smockle Looks like this should be a simple fix of subtracting 1 from the values [here](https://github.com/AtomLinter/linter-proselint/blob/3.0.0/lib/index.js#L20) (Converting the linters reported values from 1-indexed to Atom's 0-indexed values).
