### ISSUE TITLE
Not working on Atom 1.5.4

### ISSUE THREAD

**Issue by jamtur01** [AtomLinter/linter-proselint#4]
I have:

```
proselint -v
proselint, version 0.4.0
```

On OSX 10.10 with Atom 1.5.4.

I run proselint locally on a `.markdown` file and see issues.

In Atom I see a tick with "No issues". The grammar of the file is gfm. Any ideas on how to debug this?

Thanks!

**Comment by jamtur01** [comment]
I do see:

```
Error: Process execution timed out
    at /Users/james/Dropbox/home/.atom/packages/linter-proselint/node_modules/atom-linter/lib/helpers.js:79:18
```

**Comment by jamtur01** [comment]
```
{"status": "success", "data": {"errors": [{"start": 10022, "replacements": null, "end": 10024, "severity": "warning", "extent": 2, "column": 52, "message": "Use curly quotes \u201c\u201d, not straight quotes \"\".", "line": 108, "check": "butterick.symbols.curly_quotes"}, {"start": 9968, "replacements": null, "end": 9970, "severity": "warning", "extent": 2, "column": 50, "message": "Use curly quotes \u201c\u201d, not straight quotes \"\". Found 26 times elsewhere.", "line": 107, "check": "butterick.symbols.curly_quotes"}, {"start": 26167, "replacements": null, "end": 26169, "severity": "warning", "extent": 2, "column": 53, "message": "'...' is an approximation, use the ellipsis symbol '\u2026'.", "line": 329, "check": "butterick.symbols.ellipsis"}, {"start": 43523, "replacements": null, "end": 43525, "severity": "warning", "extent": 2, "column": 49, "message": "'...' is an approximation, use the ellipsis symbol '\u2026'.", "line": 570, "check": "butterick.symbols.ellipsis"}, {"start": 26111, "replacements": null, "end": 26113, "severity": "warning", "extent": 2, "column": 49, "message": "'...' is an approximation, use the ellipsis symbol '\u2026'. Found 8 times elsewhere.", "line": 328, "check": "butterick.symbols.ellipsis"}, {"start": 26750, "replacements": null, "end": 26754, "severity": "warning", "extent": 4, "column": 10, "message": "Use the multiplication symbol \u00d7, not the letter x.", "line": 348, "check": "butterick.symbols.multiplication_symbol"}, {"start": 51443, "replacements": null, "end": 51451, "severity": "warning", "extent": 8, "column": 9, "message": "Misspelling. 'monologue' is the preferred form.", "line": 734, "check": "garner.misspellings"}, {"start": 51479, "replacements": null, "end": 51487, "severity": "warning", "extent": 8, "column": 45, "message": "Misspelling. 'monologue' is the preferred form.", "line": 734, "check": "garner.misspellings"}, {"start": 4069, "replacements": null, "end": 4070, "severity": "warning", "extent": 1, "column": 193, "message": "More than 30 ppm of exclamations. Keep them under control.", "line": 44, "check": "leonard.exclamation.30ppm"}]}}
        0.80 real         0.33 user         0.21 sys
```

**Comment by Arcanemagus** [comment]
Are you able to share the file that you are running into issues with?

**Comment by jamtur01** [comment]
I am not I am afraid. I can share some details:

1. 1100 lines long / 10,000 odd words.
2. Mix of Markdown and Latex. Grammar is gfm.

**Comment by smockle** [comment]
Hi @jamtur01! Thanks for trying `linter-proselint` and for reporting this issue. As @Arcanemagus said, if you could share a file that causes a timeout in Atom (but which works via commandline `proselint`), that would greatly assist with debugging this.

@Arcanemagus I’m using `atom-linter`’s [`exec`](https://github.com/smockle/linter-proselint/blob/de0ef1843a93dd5de74d910205c989c40a94cafa/lib/index.js#L4-L13) (which is `sb-exec`’s [`exec`](https://github.com/AtomLinter/atom-linter/blob/b93598a407214b7ef545b2fddadec521f3647dc1/src/index.js#L248)) which checks its [`options` argument] (https://github.com/steelbrain/exec/blob/b91b887ca32db114725d985f411bc36c2d90c613/src/index.js#L70-L77) to set a timeout. I believe that is the source of `Error: Process execution timed out` in the Atom Editor console–does that sound right?

**Comment by Arcanemagus** [comment]
Correct, that's the source of the message. The default value is 10 seconds of waiting. If the linter is taking longer than that then we just need to specify a longer delay to `exec`, however it's also possible that the process was started and simply isn't closing properly until the timer expires and it is force killed.

**Comment by jamtur01** [comment]
After a restart I am also seeing:

```
[consistent-env] Unable to determine environment Error: Unable to determine environment(…)(anonymous function) @ /Users/james/.atom/packages/linter-proselint/node_modules/atom-linter/node_modules/consistent-env/lib/index.js:50
/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260 Uncaught BufferedProcessError: Failed to spawn command `proselint`. Make sure `proselint` is installed and on your PATH
```

**Comment by steelbrain** [comment]
@jamtur01 This new error is harmless and shouldn't break anything, but it is an indication of invalid shell configuration on your side or maybe something too slow, See https://github.com/steelbrain/consistent-env/issues/9

**Comment by jamtur01** [comment]
@steelbrain I use fish so something might not be kosher with the way Atom plugins call binaries that fish doesn't like?

**Comment by steelbrain** [comment]
@jamtur01 The fish shell is officially supported and it's support has been confirmed personally. In any case, this issue at most will 'cause Atom not to fix the $PATH issue on OSX but shouldn't break anything.

Another thing that I suspect **might** be happening is that process execution is taking a lot of time, for both your shell and proselint

**Comment by jamtur01** [comment]
Great that it works on Fish. My shell starts pretty promptly for other things and this is the only binary that times out - I've got a lot of aliases, functions, et al that all work fine.

**Comment by Arcanemagus** [comment]
Marking this as closed, @jamtur01 if you are still having issues please continue the diagnosis process in an issue on `consistent-env`.
