### ISSUE TITLE
Linting Code in Markdown File

### ISSUE THREAD

**Issue by sunjay** [AtomLinter/linter-proselint#43]
Proselint probably shouldn't be linting code in markdown files.

![screenshot from 2016-11-09 13-43-09](https://cloud.githubusercontent.com/assets/530939/20150176/774a6266-a682-11e6-8a54-1582cd1b6318.png)

**Comment by Arcanemagus** [comment]
Unfortunately there isn't a way to tell it to ignore code blocks. You can either disable `proselint` on Markdown files completely, or just ignore messages it gives you for the code blocks.

Alternatively you could also disable _just_ that rule in `proselint` through a `.proselintrc` file, although I'm not sure exactly which rule it is... possibly `misc.punctuation`?
