### ISSUE TITLE
Migrate to AtomLinter organization?

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-proselint#5]
@smockle Would you be interested in moving this to the AtomLinter org? You would still have admin rights on the repo, but would gain the help of others working on improving the code if necessary and helping with issues.

If you are interested contact myself or @steelbrain on Atom's [Slack instance](https://discuss.atom.io/t/join-us-on-slack/16638).

**Comment by smockle** [comment]
@Arcanemagus I’m very interested in that, thank you! I’ll join the Slack instance.

**Comment by Arcanemagus** [comment]
Done! :tada:

**Comment by steelbrain** [comment]
:tada: :tada: :tada:
