### ISSUE TITLE
do not ask to install 'linter' if 'atom-ide-ui' is already installed.

### ISSUE THREAD

**Issue by rriemann** [AtomLinter/linter-proselint#57]
The plugin should not trigger a popup that asks to install 'linter' if 'atom-ide-ui' is already installed.

**Comment by mbroedl** [comment]
@rriemann Can you make it work with atom-ide-ui?

For me, only linter-write-good works, but I'd prefer to use linter-proselint. It says it's running, but then the results don't show up in the list?

**Comment by rriemann** [comment]
@mbroedl  Yes it works for me with atom-ide-ui. Both proselint and write-good are running (at the same time).

**Comment by mbroedl** [comment]
Thanks @rriemann , then I need to search the error elsewhere... :-/

**Comment by mbroedl** [comment]
Now it works. Weird... Thanks a lot!

**Comment by Arcanemagus** [comment]
`atom-ide-ui` has been abandoned by Facebook, closing as `wontfix`.
