### ISSUE TITLE
Feature: Whitelist and check selection

### ISSUE THREAD

**Issue by jamtur01** [AtomLinter/linter-proselint#6]
I'd love to be able to select/control which checks are applicable.

I'd love a "WONTFIX" that ignores specific instances too but I suspect that's tricky.

**Comment by Arcanemagus** [comment]
You should be able to enable/disable checks within your `.proselintrc` file, as documented [here](https://github.com/amperser/proselint#checks). Is that not working for you?

**Comment by Arcanemagus** [comment]
Marking as closed due to a lack of response.
